//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int MaAD { get; set; }
        public string TenAD { get; set; }
        public Nullable<System.DateTime> NgaySinhAD { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public string Email { get; set; }
    }
}
