//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATHANG
    {
        public MATHANG()
        {
            this.CHITIETDONTHANGs = new HashSet<CHITIETDONTHANG>();
        }
    
        public int MaHang { get; set; }
        public string TenHang { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Giaban { get; set; }
        public string Mota { get; set; }
        public string AnhMH { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public Nullable<int> Soluongton { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaTH { get; set; }
        public Nullable<int> MaXuHuong { get; set; }
    
        public virtual ICollection<CHITIETDONTHANG> CHITIETDONTHANGs { get; set; }
        public virtual XUHUONG XUHUONG { get; set; }
        public virtual PHANLOAIHANG PHANLOAIHANG { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
